### model
### 选取eval loss最小的checkpoint进行合并
model_name_or_path: models/Qwen2.5-3B-Instruct
adapter_name_or_path: output/qwen3b_instruct_ts_lora_llamafactory/checkpoint-4000
template: qwen
finetuning_type: lora

### export
export_dir: models/T_3b_lora-sft_step4000
export_size: 1
export_device: cpu
export_legacy_format: false